server:
  port: '8761'

spring:
  application:
    name: SERVICE-REGISTRY

eureka:
  instance:
    hostname: ${DOCKER_HOST:localhost}
  client:
    fetch-registry: 'false'
    register-with-eureka: 'false'
