version: '3.8'

services:

  db:
    image: postgres:latest
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: moneron
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  department-service:
    build:
      dockerfile: department-service/Dockerfile
    container_name: department-service
    ports:
      - "8081:8081"
    depends_on:
      - db

  staff-service:
    build:
      dockerfile: staff-service/Dockerfile
    container_name: staff-service
    ports:
      - "8082:8082"x
    depends_on:
      - db

  expense-tracker:
    build:
      dockerfile: expense-tracker/Dockerfile
    container_name: expense-tracker
    image: moneron
    ports:
      - "8083:8083"
    depends_on:
      - db

volumes:
  postgres_data: