version: '3.8'

services:

  db:
    image: postgres:latest
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: moneron
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq

  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    environment:
      - "STORAGE_TYPE=mem"
    ports:
      - "9411:9411"

  config-server:
    image: anatolydudko/config-server:3.2.5
    container_name: config-server
    ports:
      - "8888:8888"
    environment:
      EUREKA_SERVICE_URL: http://eureka-server:8761/eureka/
      CONFIG_SERVER_GIT_URI: https://github.com/aDudko/config-repo.git
      CONFIG_SERVER_GIT_USERNAME: ''
      CONFIG_SERVER_GIT_PASSWORD: ''
      CONFIG_SERVER_GIT_BRANCH: moneron-docker

  eureka-server:
    image: anatolydudko/eureka-server:3.2.5
    container_name: eureka-server
    ports:
      - "8761:8761"
    depends_on:
      - config-server
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka
      CONFIG_SERVER_URL: http://config-server:8888

  api-gateway:
    image: anatolydudko/api-gateway:3.2.5
    container_name: api-gateway
    ports:
      - "8787:8787"
    depends_on:
      - rabbitmq
      - zipkin
      - eureka-server
    environment:
      EUREKA_SERVICE_URL: http://eureka-server:8761/eureka/

networks:
  rabbitmq:
    driver: bridge

volumes:
  postgres_data: