server:
  port: '8888'

spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          clone-on-start: 'true'
          uri: https://github.com/aDudko/config-repo.git
          default-label: moneron-dev
